- hosts : test  
  connection: local                                      
 # remote_user : root                           #通过root用户执行
  tasks :
  - name : test_conn                           
    shell : touch /Users/mengshishang/mms/file/demo/01-mss/mengshishang/script/ansible_script/test.txt
  # - name : install nginx
  #   shell : yum install nginx
  - name : copy hugo static
    copy: 
      src:  /Users/mengshishang/mss/content/posts/
      dest:  /Users/mengshishang/mms/file/demo/01-mss/mengshishang/content/posts/